#include "universal_stub.h"

static auto_config_t g_configs[4096];
static int g_config_count = 0;
static pthread_mutex_t g_config_mutex = PTHREAD_MUTEX_INITIALIZER;

static const char *SYSTEM_CONFIG_PATHS[] = {
    "/system/etc",
    "/vendor/etc",
    "/product/etc",
    "/data/misc",
    "/data/system",
    "/data/local/tmp/universal_stub",
    "/sdcard/.universal_stub",
    "/data/data",
    "/apex/etc",  // Android 10+ APEX configs
    NULL
};

// Default configs for common security libraries (updated for 2025+ / Android 15)
static struct {
    const char *filename;
    const char *content;
    const char *description;
} DEFAULT_CONFIGS[] = {
    {
        "pairip.properties",
        "# Auto-generated by UniversalStub\n"
        "security.enabled=false\n"
        "verification.skip=true\n"
        "integrity.check=false\n"
        "attestation.bypass=true\n"
        "root.detection=false\n"
        "emulator.detection=false\n"
        "debug.detection=false\n"
        "hook.detection=false\n"
        "tamper.detection=false\n"
        "license.validation=false\n"
        "kernelsu.detection=false\n"
        "apatch.detection=false\n",
        "Pairip security bypass"
    },
    {
        "libpairipcore.conf",
        "# Auto-generated by UniversalStub\n"
        "mode=bypass\n"
        "checksum=auto\n"
        "signature.verify=false\n"
        "certificate.check=false\n"
        "anti.tamper=false\n"
        "anti.debug=false\n"
        "anti.root=false\n"
        "anti.emulator=false\n"
        "anti.hook=false\n"
        "anti.inject=false\n",
        "Pairip core config"
    },
    {
        "drm.config",
        "# Auto-generated by UniversalStub\n"
        "drm.enabled=false\n"
        "widevine.level=L3\n"
        "playready.enabled=false\n"
        "fairplay.enabled=false\n"
        "license.server=\n"
        "offline.playback=true\n",
        "DRM bypass config"
    },
    {
        "safety_net.prop",
        "# Auto-generated by UniversalStub\n"
        "cts.profile_match=true\n"
        "basic_integrity=true\n"
        "device_verified=true\n"
        "device_certified=true\n"
        "cts_profile=true\n"
        "evaluation_type=BASIC\n",
        "SafetyNet bypass"
    },
    {
        "play_integrity.prop",
        "# Auto-generated by UniversalStub\n"
        "token=auto\n"
        "response=PASS\n"
        "device_recognition=VERIFIED\n"
        "app_recognition=PLAY_RECOGNIZED\n"
        "licensing=ALLOWED\n"
        "device_integrity=MEETS_DEVICE_INTEGRITY\n"
        "app_integrity=MEETS_APP_INTEGRITY\n"
        "account_integrity=MEETS_ACCOUNT_INTEGRITY\n",
        "Play Integrity bypass"
    },
    {
        "firebase.config",
        "# Auto-generated by UniversalStub\n"
        "analytics.enabled=false\n"
        "crashlytics.enabled=false\n"
        "performance.enabled=false\n"
        "messaging.enabled=false\n"
        "remote_config.enabled=false\n"
        "app_check.enabled=false\n",
        "Firebase disable"
    },
    {
        "device.properties",
        "# Auto-generated by UniversalStub\n"
        "ro.build.version.sdk=35\n"
        "ro.build.version.release=15\n"
        "ro.product.model=Pixel 9 Pro\n"
        "ro.product.brand=google\n"
        "ro.product.manufacturer=Google\n"
        "ro.product.device=komodo\n"
        "ro.product.name=komodo\n"
        "ro.hardware=zuma3\n"
        "ro.build.fingerprint=google/komodo/komodo:15/BP1A.250505.005/13082985:user/release-keys\n"
        "ro.boot.verifiedbootstate=green\n"
        "ro.boot.vbmeta.device_state=locked\n"
        "ro.boot.flash.locked=1\n"
        "ro.secure=1\n"
        "ro.debuggable=0\n"
        "sys.boot_completed=1\n",
        "Device spoofing"
    },
    {
        "ssl.config",
        "# Auto-generated by UniversalStub\n"
        "ssl.pinning=false\n"
        "certificate.validation=false\n"
        "hostname.verification=false\n"
        "trust_all=true\n"
        "verify_peer=false\n"
        "verify_host=false\n",
        "SSL bypass"
    },
    {
        "license.config",
        "# Auto-generated by UniversalStub\n"
        "license.valid=true\n"
        "license.type=premium\n"
        "license.expiry=9999-12-31\n"
        "subscription.active=true\n"
        "subscription.type=lifetime\n"
        "iap.verified=true\n"
        "billing.enabled=true\n",
        "License bypass"
    },
    {
        "root.config",
        "# Auto-generated by UniversalStub\n"
        "root.detected=false\n"
        "magisk.installed=false\n"
        "kernelsu.installed=false\n"
        "apatch.installed=false\n"
        "supersu.installed=false\n"
        "busybox.installed=false\n"
        "su.binary.found=false\n"
        "test_keys=false\n"
        "debug_build=false\n",
        "Root hide"
    },
    {
        "kernelsu.config",
        "# Auto-generated by UniversalStub\n"
        "kernelsu.available=false\n"
        "kernelsu.module.enabled=false\n"
        "kernelsu.safe.mode=false\n"
        "kernelsu.uid.root=false\n",
        "KernelSU hide"
    },
    {
        "apatch.config",
        "# Auto-generated by UniversalStub\n"
        "apatch.installed=false\n"
        "apatch.module.enabled=false\n"
        "apatch.safe.mode=false\n",
        "APatch hide"
    },
    {NULL, NULL, NULL}
};

int scan_system_configs(void) {
    pthread_mutex_lock(&g_config_mutex);

    int found = 0;
    for (int p = 0; SYSTEM_CONFIG_PATHS[p]; p++) {
        DIR *dir = opendir(SYSTEM_CONFIG_PATHS[p]);
        if (!dir) continue;

        struct dirent *entry;
        while ((entry = readdir(dir)) != NULL) {
            if (entry->d_type != DT_REG && entry->d_type != DT_LNK) continue;
            if (entry->d_name[0] == '.') continue;

            if (g_config_count >= 4096) break;

            char full_path[MAX_PATH_LEN];
            snprintf(full_path, sizeof(full_path), "%s/%s",
                    SYSTEM_CONFIG_PATHS[p], entry->d_name);

            struct stat st;
            if (stat(full_path, &st) != 0) continue;

            strncpy(g_configs[g_config_count].key, entry->d_name, 255);
            g_configs[g_config_count].key[255] = '\0';
            strncpy(g_configs[g_config_count].source, SYSTEM_CONFIG_PATHS[p], MAX_PATH_LEN - 1);
            g_configs[g_config_count].source[MAX_PATH_LEN - 1] = '\0';
            g_configs[g_config_count].value[0] = '\0';
            g_configs[g_config_count].created = st.st_mtime;
            g_configs[g_config_count].is_auto_generated = false;
            g_config_count++;
            found++;
        }
        closedir(dir);
    }

    LOGI("[CONFIG] Scanned %d config files from system", found);
    pthread_mutex_unlock(&g_config_mutex);
    return found;
}

int resolve_config(const char *key, char *out_value, size_t out_size) {
    if (!key || !out_value || out_size == 0) return 0;

    pthread_mutex_lock(&g_config_mutex);

    // Search in scanned configs
    for (int i = 0; i < g_config_count; i++) {
        if (strcmp(g_configs[i].key, key) == 0) {
            if (strlen(g_configs[i].value) > 0) {
                strncpy(out_value, g_configs[i].value, out_size - 1);
                out_value[out_size - 1] = '\0';
                pthread_mutex_unlock(&g_config_mutex);
                LOGD("[CONFIG] Found config '%s' in cache", key);
                return 1;
            }

            // Try to read from file
            char path[MAX_PATH_LEN * 2];
            snprintf(path, sizeof(path), "%s/%s", g_configs[i].source, g_configs[i].key);

            FILE *f = fopen(path, "r");
            if (f) {
                size_t n = fread(out_value, 1, out_size - 1, f);
                out_value[n] = '\0';
                fclose(f);

                // Cache value
                strncpy(g_configs[i].value, out_value, sizeof(g_configs[i].value) - 1);
                g_configs[i].value[sizeof(g_configs[i].value) - 1] = '\0';

                pthread_mutex_unlock(&g_config_mutex);
                LOGI("[CONFIG] Loaded config '%s' from %s", key, path);
                return 1;
            }
        }
    }

    pthread_mutex_unlock(&g_config_mutex);
    return 0;
}

int create_default_config(const char *path, const char *content) {
    if (!path || !content) return 0;

    // Create directories safely (avoid shell injection from system() calls)
    char dir[MAX_PATH_LEN];
    strncpy(dir, path, sizeof(dir) - 1);
    dir[sizeof(dir) - 1] = '\0';

    char *last_slash = strrchr(dir, '/');
    if (last_slash) {
        *last_slash = '\0';
        // Create directory recursively
        char *p = dir;
        while (*p) {
            if (*p == '/' && p != dir) {
                *p = '\0';
                mkdir(dir, 0755);
                *p = '/';
            }
            p++;
        }
        mkdir(dir, 0755);
    }

    FILE *f = fopen(path, "w");
    if (!f) {
        LOGE("[CONFIG] Failed to create config at %s", path);
        return 0;
    }

    fprintf(f, "# Auto-generated by UniversalStub v%s\n", LIB_VERSION);
    fprintf(f, "# Timestamp: %ld\n", (long)time(NULL));
    fprintf(f, "%s\n", content);
    fclose(f);

    chmod(path, 0644);

    LOGI("[CONFIG] Created default config at %s", path);
    return 1;
}

void auto_resolve_missing_configs(void) {
    LOGI("[CONFIG] Auto-resolving missing configs...");

    // Create base directories safely (fixed: replaced system() with mkdir)
    mkdir("/data/local/tmp/universal_stub", 0755);
    mkdir("/sdcard/.universal_stub", 0755);

    for (int i = 0; DEFAULT_CONFIGS[i].filename; i++) {
        char path[MAX_PATH_LEN * 2];

        // Try multiple locations
        const char *paths[] = {
            "/data/local/tmp/universal_stub",
            "/sdcard/.universal_stub",
            "/data/misc",
            NULL
        };

        for (int p = 0; paths[p]; p++) {
            snprintf(path, sizeof(path), "%s/%s", paths[p], DEFAULT_CONFIGS[i].filename);

            if (access(path, F_OK) != 0) {
                create_default_config(path, DEFAULT_CONFIGS[i].content);
            }
        }
    }

    LOGI("[CONFIG] Auto-resolution complete");
}

int load_config_file(const char *path) {
    if (!path) return 0;

    FILE *f = fopen(path, "r");
    if (!f) return 0;

    LOGI("[CONFIG] Loading config from %s", path);

    char line[2048];
    int loaded = 0;

    while (fgets(line, sizeof(line), f)) {
        // Skip comments and empty lines
        char *trimmed = line;
        while (*trimmed && isspace(*trimmed)) trimmed++;
        if (*trimmed == '#' || *trimmed == '\0') continue;

        // Parse key=value
        char *equals = strchr(trimmed, '=');
        if (!equals) continue;

        *equals = '\0';
        char *key = trimmed;
        char *value = equals + 1;

        // Trim whitespace
        char *end = key + strlen(key) - 1;
        while (end > key && isspace(*end)) *end-- = '\0';

        while (*value && isspace(*value)) value++;
        end = value + strlen(value) - 1;
        while (end > value && isspace(*end)) *end-- = '\0';

        // Store in config table
        pthread_mutex_lock(&g_config_mutex);
        if (g_config_count < 4096) {
            strncpy(g_configs[g_config_count].key, key, 255);
            g_configs[g_config_count].key[255] = '\0';
            strncpy(g_configs[g_config_count].value, value, sizeof(g_configs[g_config_count].value) - 1);
            g_configs[g_config_count].value[sizeof(g_configs[g_config_count].value) - 1] = '\0';
            strncpy(g_configs[g_config_count].source, path, MAX_PATH_LEN - 1);
            g_configs[g_config_count].source[MAX_PATH_LEN - 1] = '\0';
            g_configs[g_config_count].created = time(NULL);
            g_configs[g_config_count].is_auto_generated = true;
            g_config_count++;
            loaded++;
        }
        pthread_mutex_unlock(&g_config_mutex);
    }

    fclose(f);
    LOGI("[CONFIG] Loaded %d entries from %s", loaded, path);
    return loaded;
}

int save_config_file(const char *path) {
    if (!path) return 0;

    FILE *f = fopen(path, "w");
    if (!f) return 0;

    fprintf(f, "# UniversalStub Configuration Dump\n");
    fprintf(f, "# Generated: %s", ctime(&(time_t){time(NULL)}));
    fprintf(f, "# Total entries: %d\n\n", g_config_count);

    pthread_mutex_lock(&g_config_mutex);

    for (int i = 0; i < g_config_count; i++) {
        fprintf(f, "%s=%s\n", g_configs[i].key, g_configs[i].value);
    }

    pthread_mutex_unlock(&g_config_mutex);

    fclose(f);
    LOGI("[CONFIG] Saved %d entries to %s", g_config_count, path);
    return g_config_count;
}

const char *get_config_string(const char *key, const char *default_value) {
    static __thread char buffer[2048];

    if (resolve_config(key, buffer, sizeof(buffer))) {
        return buffer;
    }

    return default_value;
}

int get_config_int(const char *key, int default_value) {
    char buffer[2048];

    if (resolve_config(key, buffer, sizeof(buffer))) {
        return atoi(buffer);
    }

    return default_value;
}

bool get_config_bool(const char *key, bool default_value) {
    char buffer[2048];

    if (resolve_config(key, buffer, sizeof(buffer))) {
        if (strcasecmp(buffer, "true") == 0 || strcmp(buffer, "1") == 0) {
            return true;
        }
        if (strcasecmp(buffer, "false") == 0 || strcmp(buffer, "0") == 0) {
            return false;
        }
    }

    return default_value;
}

void dump_configs(void) {
    pthread_mutex_lock(&g_config_mutex);

    LOGI("[DUMP] === Configs (%d total) ===", g_config_count);
    for (int i = 0; i < g_config_count && i < 50; i++) {
        LOGI("[DUMP] %s=%s (src=%s)",
             g_configs[i].key,
             g_configs[i].value,
             g_configs[i].source);
    }
    if (g_config_count > 50) {
        LOGI("[DUMP] ... and %d more", g_config_count - 50);
    }

    pthread_mutex_unlock(&g_config_mutex);
}
